Improve set-wallpaper

diff --git a/bin/set-wallpaper b/bin/set-wallpaper
--- a/bin/set-wallpaper
+++ b/bin/set-wallpaper
@@ -1,14 +1,42 @@
 #!/bin/sh
 set -eu
 
-if [ -d ~/Pictures/Wallpapers ]
-then
-    find ~/Pictures/Wallpapers -type f -a \
-         \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" \) \
-        | unsort --seed="$(date +%Y%m%d)" \
-        | head -1 \
-        | xargs xwallpaper --zoom
-elif [ -x /usr/local/bin/openbsd-wallpaper ]
-then /usr/local/bin/openbsd-wallpaper
-else xsetroot -solid black
-fi
+_set_wallpaper() {
+    if [ -n "${SWAYSOCK:-}" ]
+    then sway_wallpaper "$1"
+    elif hash xwallpaper 2>/dev/null
+    then xwallpaper --zoom "$1"
+    elif hash xsetroot 2>/dev/null
+    then xsetroot -solid black
+    else
+        echo >&2 'E: cannot set wallpaper'
+        exit 2
+    fi
+}
+
+sway_wallpaper() {
+    swaymsg "output * background '$1' fill #000000"
+}
+
+main() {
+    case "${1:-random}" in
+        daily)
+            seed="$(date +%Y%m%d)"
+            ;;
+        hourly)
+            seed="$(date +%Y%m%d:%H)"
+            ;;
+        random|*)
+            seed=$(random | head -1)
+            ;;
+    esac
+    fname=$(find ~/Pictures/Wallpapers -type f -a \
+                 \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" \) \
+                | unsort --seed=$seed \
+                | head -1)
+    echo "$fname"
+    _set_wallpaper "$fname"
+    exit 0
+}
+
+main "$@"
